export const USER_CHECK_REQUEST = 'USER_CHECK_REQUEST';
export const USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS';
export const USER_CHECK_FAILURE = 'USER_CHECK_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE';

export const READ_QUESTIONS_REQUEST = 'READ_QUESTIONS_REQUEST';
export const READ_QUESTIONS_SUCCESS = 'READ_QUESTIONS_SUCCESS';
export const READ_QUESTIONS_FAILURE = 'READ_QUESTIONS_FAILURE';

export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_FAILURE = 'UPDATE_QUESTION_FAILURE';

export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';

export const SEARCH_QUESTION_REQUEST = 'SEARCH_QUESTION_REQUEST';
export const SEARCH_QUESTION_SUCCESS = 'SEARCH_QUESTION_SUCCESS';
export const SEARCH_QUESTION_FAILURE = 'SEARCH_QUESTION_FAILURE';
