export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const USER_CHECK_REQUEST = 'USER_CHECK_REQUEST';
export const USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS';
export const USER_CHECK_FAILURE = 'USER_CHECK_FAILURE';
